### ISSUE TITLE
handle bad dev token gracefully

### ISSUE THREAD

**Issue by sh3nan1gans** [ClearBlade/cb-dev-kit#6]
Tried running hot reload for a portal when I had a bad dev token and I got an error that wasn't helpful. (Note the 'Full Error: {}' log) I'm assuming we don't get a proper error message when trying to connect via MQTT so maybe we should call the /admin/checkauth HTTP endpoint before trying to connect.

`Clarks-MacBook-Pro:ClearBladeDeploymentKit clarkbynum$ npm run start:provision

> testsys@1.0.0 start:provision /Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit
> cb-dev-kit clearblade-hot-reload -portal=provision -noSSL

> testsys@1.0.0 start:clearblade-hot-reload /Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit
> npm-run-all --parallel start:watch start:server

> testsys@1.0.0 start:watch /Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit
> webpack --config webpack.config.js --config-name clearblade-hot-reload

> testsys@1.0.0 start:server /Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit
> clearblade-hot-reload start

Error connecting MQTT on port 1883. 
Please check that the -messagePort is set to correct MQTT port the console is running on. 
Also, if pointing hotReload at a local platform, please set -noSSL to true. 
If pointing at a production system and your certificate authority is not DigiCert, you must use -caPath to provide the absolute path of your CA. 
Full Error: {}
/Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit/node_modules/@clearblade/clearblade-hot-reload/cmds/start.js:58
      throw new Error();
      ^

Error
    at Object.onFailure (/Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit/node_modules/@clearblade/clearblade-hot-reload/cmds/start.js:58:13)
    at MqttClient.onFailure (/Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit/node_modules/clearblade/ClearBlade.js:1124:15)
    at MqttClient.emit (events.js:200:13)
    at MqttClient._handleConnack (/Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit/node_modules/mqtt/lib/client.js:697:10)
    at MqttClient._handlePacket (/Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit/node_modules/mqtt/lib/client.js:282:12)
    at process (/Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit/node_modules/mqtt/lib/client.js:226:12)
    at Writable.writable._write (/Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit/node_modules/mqtt/lib/client.js:236:5)
    at doWrite (/Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/Users/clarkbynum/Developer/golang/src/clearblade-deployment-kit/ClearBladeDeploymentKit/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:194:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testsys@1.0.0 start:server: `clearblade-hot-reload start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testsys@1.0.0 start:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/clarkbynum/.npm/_logs/2019-07-09T18_13_16_321Z-debug.log
ERROR: "start:server" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testsys@1.0.0 start:clearblade-hot-reload: `npm-run-all --parallel start:watch start:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testsys@1.0.0 start:clearblade-hot-reload script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/clarkbynum/.npm/_logs/2019-07-09T18_13_16_383Z-debug.log`

**Comment by sh3nan1gans** [comment]
Had to run cb-cli target in order to reauth and get a new valid token

**Comment by aalcott14** [comment]
resolved in @clearblade/clearblade-hot-reload@1.1.6
