### ISSUE TITLE
Generate command not working

### ISSUE THREAD

**Issue by amoujaes1** [ClearBlade/cb-dev-kit#7]
Allisons-MacBook-Pro-2:files allisonmoujaes$ cb-dev-kit generate

> @clearblade/cb-dev-kit@1.1.0 plop /usr/local/lib/node_modules/@clearblade/cb-dev-kit
> plop --plopfile cmds/generate.js

fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/Users/allisonmoujaes/Desktop/ClearBlade_Test/files/code/libraries'
    at Object.readdirSync (fs.js:786:3)
    at getLibraries (/usr/local/lib/node_modules/@clearblade/cb-dev-kit/templates/getAssets.js:67:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/@clearblade/cb-dev-kit/generators/library.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by aalcott14** [comment]
resolved in @clearblade/cb-dev-kit@1.1.2
